### ISSUE TITLE
Compatibility with Behdad's fork of FontTools

### ISSUE THREAD

**Issue by andyclymer** [typesupply/woffTools#1]
I found a couple small places where woffTools isn't compatible with Behdad's fork of FontTools, but making the fix would break compatibility with the SourceForge version. I wanted to ask before submitting the change, would you plan be to keep woffTools compatible with one or the other?

What I found is getSearchRange() called from **init**.py and validate.py now needs an "itemSize" argument. The version of FontTools on SourceForge used 16 as the value for itemSize but I guess it looks like the this value needs to change from time to time:
https://github.com/behdad/fonttools/search?utf8=%E2%9C%93&q=getSearchRange

Behdad's version:
https://github.com/behdad/fonttools/blob/master/Lib/fontTools/ttLib/__init__.py#L958

SourceForge version:
http://sourceforge.net/p/fonttools/code/ci/master/tree/Lib/fontTools/ttLib/sfnt.py#l281

Should I go ahead and submit this fix? Or would you try to keep it compatible with both versions?

Andy

**Comment by behdad** [comment]
Let me try to address this in my fonttools.

**Comment by behdad** [comment]
Fixed in my fonttools.

**Comment by andyclymer** [comment]
Amazing! Thanks, Behdad!
